### ISSUE TITLE
No way to output file to a different directory

### ISSUE THREAD

**Issue by TheClaus** [donmelton/other_video_transcoding#45] opened 2020-06-18 14:15 UTC
I noticed that there isn't a switch to output the file to a different directory like there is with your other app.  Is this a limitation or did I miss something?

I am running a powershell script that looks for files in one folder and converts them.  Currently it outputs to the location of my script file.  Would like it to output to a different folder if possible.

**Comment by donmelton** [comment] 2020-06-18 14:26
@TheClaus All output going to the current working directory is intentional and by design. And I have no plans to change that. You can already decide where your output will go simply by using the `cd` command before you invoke `other-transcode`. So it's not a limitation either.

Your request is actually a duplicate of issue #9 (and issue #44) where I've detailed my reasoning for not implementing this. Sorry.

**Closed by donmelton** 2020-06-18 14:26 UTC
Labels: enhancement

**Comment by asheimo** [comment] 2020-06-18 14:36
@TheClaus In your powershell script you can add a working directory command to put the output where you want to.  My 2 cents worth.
