### ISSUE TITLE
Adding FFMpeg Filters - "Degraining"

### ISSUE THREAD

**Issue by TehMaster** [donmelton/other_video_transcoding#78] opened 2020-10-20 18:11 UTC
Hey @donmelton and Community,

Is there a way to add additional FFMPEG filters to degrain/denoise content? I would like to try adding -nlmeans or -hqdn3d if possible as i have some noisy content that drives me up a wall, and don't quite see how that's possible.

Thanks All!

**Comment by donmelton** [comment] 2020-10-20 21:04
@TehMaster I'm sorry you're having this problem but other than modifying the output of the command line generated by `other-transcode` via the`--dry-run` option, or modifying the code to `other-transcode` itself, there's no way to do that.

And that's by design. Let me explain...

The filter syntax in `ffmpeg` is _much_ more complicated than, say, the filter syntax in `HandBrakeCLI`. Other than adding single-option "macros" for these Digital Noise Reduction (DNR) filters (like the `--detelecine` option) there's not an easy way to do this other than just becoming `ffmpeg` itself. Which I'm not going to do.

More importantly, the focus of `other-transcode` is leveraging hardware video encoders and decoders for high performance while still maintaining high quality. And these DNR filters are slow. And I mean really slow. Worse, they slow down the whole hardware pipeline because the filtering must be done in software.

If you want to experiment with these filters, I recommend using my original tool, `transcode-video`, available here:

https://github.com/donmelton/video_transcoding

But be advised that when `nlmeans` or `hqdn3d` are applied with enough spatial and temporal strength to make a difference and remove noise in a way that you can actually see, the following problems often occur:

* People look like plastic (the "Barbie doll" effect) because there's too much smoothing of surfaces that aren't noisy.
* Color banding appears in other surfaces because, again, there's too much smoothing in content that isn't noisy.
* Ghosting and added noise appear during motion.

I've spent a LOT of time experimenting with these filters and I've never found a case where I thought the transcoding time and iteration necessary to tune the settings was worth it.

Seriously, you're much better off transcoding to 10-bit HEVC format and leveraging the "faux" DNR effect of HEVC itself.

Does that help?

**Comment by TehMaster** [comment] 2020-10-20 21:42
Indeed it does; tremendously so. I always appreciate your wisdom and thoughts on a subject as you and the "crew" are often leaps ahead of me in hands on experience. My only real experience with removing grain/noise is with handbrake, and it seems its much more complicated in ffmpeg. I also think i would definitely run into the barbie doll effect as the noise is mainly in the set/environment, and not the actors themselves.

I suppose this is best left alone. ;)

Appreciated as always Don!

**Comment by donmelton** [comment] 2020-10-20 21:48
@TehMaster No problem. I'll close this now but, as always, feel free to continue commenting or open new issues.

And, once again, thanks so much for using my tools!

**Closed by donmelton** 2020-10-20 21:48 UTC
Labels: question
