### ISSUE TITLE
What am I doing wrong in this surround to stereo mp4 attempt?

### ISSUE THREAD

**Issue by loshlee** [donmelton/other_video_transcoding#169] opened 2022-11-06 02:52 UTC
I've tried many versions of this command on my Silicon Mac. What's the simplest way to alter it so that it will give me .mp4 output? I can get .mkv, no problem, but I'm hoping for .mp4. Thanks!

other-transcode --debug --copy-video --mp4 --main-audio 1=stereo inputsurroundmovie.mp4
                                                  
Here's the pertinent part of the error message appearing in Terminal when I try it: "other-transcode: output file already exists: inputsurroundmovie.mp4"
It appears that the issue might be solved by providing an output filename so that it differs from the input filename. How can I do it? Thanks again!

**Comment by ttyS0** [comment] 2022-11-06 02:56
You need to put your source in a different directory. For example, 

```
mkdir src
mv inputsurroundmovie.mp4 src/
other-transcode --debug --copy-video --mp4 --main-audio 1=stereo src/inputsurroundmovie.mp4
```

The transcoded output will be in your current working directory. This pattern is by design. Talking about an `--output` option makes Don's eye twitch. We like Don, and we like him even more when his eye's not twitching. 😎

**Comment by loshlee** [comment] 2022-11-06 03:07
Thanks. I kept getting in deeper with my tries, so I guess I needed a break. I thought I had ruled that out already, but no. It is the solution. In my case, I can also get the desired result by renaming the input to m4v, but that's not always workable Thanks again.

**Closed** 2022-11-06 03:10 UTC

**Comment by donmelton** [comment] 2022-11-06 03:24
@ttyS0 Thanks! 👍
