### ISSUE TITLE
Incorrect Video Tags For Apple Devices With hevc + mp4 Output

### ISSUE THREAD

**Issue by buffaloseven** [donmelton/other_video_transcoding#97] opened 2021-02-11 18:22 UTC
Saw that this was an issue before and can be fixed by adding the `tag:v hvc1` flag to ffmpeg. That said, when running the latest version on macOS:

`other-transcode --hevc --mp4 ./path/to/file.mkv`

other-transcode shows this in the log:

```
ffmpeg -loglevel error -stats -i ./Arrival/Arrival_t00.mkv -map 0:0 -c:v hevc_videotoolbox -b:v 8000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v "title=" -disposition:v default -map 0:1 -c:a:0 ac3 -b:a:0 640k -metadata:s:a:0 "title=" -disposition:a:0 default -sn -metadata:g "title=" -movflags disable_chpl Arrival_t00.mp4
```

With no tag flag being set. Is there a regression somewhere that has stopped this from working?

**Comment by donmelton** [comment] 2021-02-11 20:51
@buffaloseven I'm sorry you're having this problem. But the code to add the tag is still in `other-transcode` when the `--hevc` and `--mp4` options are used. So I'm not sure why you're seeing it in your `.log` file. Can you verify which version of `other-transcode` you're using?

Also, can you attach the `.log` file here? Thanks.

**Comment by buffaloseven** [comment] 2021-02-11 21:05
Environment:
`gem list | grep "other_video_transcoding"`: `other_video_transcoding (0.7.0)`
`which ruby`: `/usr/local/opt/ruby/bin/ruby`
`which gem`: `/usr/local/opt/ruby/bin/gem`
`ruby -v`: `ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]`

A log file (up to the actual transcoding part):
```
ffmpeg started on 2021-02-11 at 15:02:24
Report written to "_ffmpeg_69784_31548.mp4.log"
Log level: 40
Command line:
ffmpeg -loglevel error -stats -i ./Arrival/Arrival_t00.mkv -map 0:0 -c:v hevc_videotoolbox -b:v 8000k -color_primaries:v bt709 -color_trc:v bt709 -colorspace:v bt709 -metadata:s:v "title=" -disposition:v default -map 0:1 -c:a:0 ac3 -b:a:0 640k -metadata:s:a:0 "title=" -disposition:a:0 default -sn -metadata:g "title=" -movflags disable_chpl Arrival_t00.mp4
ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with Apple clang version 12.0.0 (clang-1200.0.32.29)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1_9 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-videotoolbox
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[h264 @ 0x7fe58b008800] Reinit context to 1920x1088, pix_fmt: yuv420p
[dca @ 0x7fe58b009400] Forcing XLL recovery mode
[matroska,webm @ 0x7fe58a809600] Could not find codec parameters for stream 6 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x7fe58a809600] Could not find codec parameters for stream 7 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x7fe58a809600] Could not find codec parameters for stream 8 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x7fe58a809600] Could not find codec parameters for stream 9 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x7fe58a809600] Could not find codec parameters for stream 10 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[matroska,webm @ 0x7fe58a809600] Could not find codec parameters for stream 11 (Subtitle: hdmv_pgs_subtitle (pgssub)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, matroska,webm, from './Arrival/Arrival_t00.mkv':
  Metadata:
    title           : Arrival
    encoder         : libmakemkv v1.15.4 (1.3.10/1.5.2) darwin(x64-release)
    creation_time   : 2021-02-03T17:58:34.000000Z
  Duration: 01:56:22.98, start: 0.000000, bitrate: 35106 kb/s
    Chapter #0:0: start 0.000000, end 589.755833
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 589.755833, end 1053.635917
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 1053.635917, end 1408.281875
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 1408.281875, end 2033.990292
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 2033.990292, end 2461.500708
    Metadata:
      title           : Chapter 05
    Chapter #0:5: start 2461.500708, end 3146.101292
    Metadata:
      title           : Chapter 06
    Chapter #0:6: start 3146.101292, end 3454.534417
    Metadata:
      title           : Chapter 07
    Chapter #0:7: start 3454.534417, end 3786.449333
    Metadata:
      title           : Chapter 08
    Chapter #0:8: start 3786.449333, end 4169.206708
    Metadata:
      title           : Chapter 09
    Chapter #0:9: start 4169.206708, end 4569.398167
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 4569.398167, end 5121.533083
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 5121.533083, end 5736.981250
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 5736.981250, end 6326.320000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 6326.320000, end 6982.976000
    Metadata:
      title           : Chapter 14
    Stream #0:0(eng): Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc
    Metadata:
      BPS-eng         : 27341256
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 167424
      NUMBER_OF_BYTES-eng: 23865416837
      SOURCE_ID-eng   : 001011
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 7.1, s32p (24 bit) (default)
    Metadata:
      title           : Surround 7.1
      BPS-eng         : 4207353
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 654654
      NUMBER_OF_BYTES-eng: 3672480936
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:2(eng): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 1536 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 1509000
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 654654
      NUMBER_OF_BYTES-eng: 1317163848
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:3(fra): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 640000
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 218218
      NUMBER_OF_BYTES-eng: 558638080
      SOURCE_ID-eng   : 001101
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:4(spa): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 640000
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 218218
      NUMBER_OF_BYTES-eng: 558638080
      SOURCE_ID-eng   : 001102
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:5(eng): Audio: ac3, 48000 Hz, 5.1(side), fltp, 640 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 640000
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 218218
      NUMBER_OF_BYTES-eng: 558638080
      SOURCE_ID-eng   : 001103
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:6(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 32796
      DURATION-eng    : 01:48:58.469437500
      NUMBER_OF_FRAMES-eng: 2444
      NUMBER_OF_BYTES-eng: 26804982
      SOURCE_ID-eng   : 001200
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:7(eng): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 36145
      DURATION-eng    : 01:48:58.677979166
      NUMBER_OF_FRAMES-eng: 2878
      NUMBER_OF_BYTES-eng: 29542793
      SOURCE_ID-eng   : 001201
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:8(fra): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 30665
      DURATION-eng    : 01:49:17.196479166
      NUMBER_OF_FRAMES-eng: 2528
      NUMBER_OF_BYTES-eng: 25135266
      SOURCE_ID-eng   : 001202
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:9(fra): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 669
      DURATION-eng    : 01:44:34.831062500
      NUMBER_OF_FRAMES-eng: 56
      NUMBER_OF_BYTES-eng: 525318
      SOURCE_ID-eng   : 001202
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:10(spa): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 29791
      DURATION-eng    : 01:49:16.570854166
      NUMBER_OF_FRAMES-eng: 2278
      NUMBER_OF_BYTES-eng: 24416334
      SOURCE_ID-eng   : 001203
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:11(spa): Subtitle: hdmv_pgs_subtitle
    Metadata:
      BPS-eng         : 573
      DURATION-eng    : 01:44:32.954187500
      NUMBER_OF_FRAMES-eng: 50
      NUMBER_OF_BYTES-eng: 449826
      SOURCE_ID-eng   : 001203
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> hevc (hevc_videotoolbox))
  Stream #0:1 -> #0:1 (dts (dca) -> ac3 (native))
Press [q] to stop, [?] for help
[dca @ 0x7fe58981e200] Forcing XLL recovery mode
[h264 @ 0x7fe58880d800] Reinit context to 1920x1088, pix_fmt: yuv420p
[graph_1_in_0_1 @ 0x7fe58a0046c0] tb:1/48000 samplefmt:s32p samplerate:48000 chlayout:0x63f
[format_out_0_1 @ 0x7fe58a004cc0] auto-inserting filter 'auto_resampler_0' between the filter 'Parsed_anull_0' and the filter 'format_out_0_1'
[auto_resampler_0 @ 0x7fe58a005700] ch:8 chl:7.1 fmt:s32p r:48000Hz -> ch:6 chl:5.1(side) fmt:fltp r:48000Hz
[graph 0 input from stream 0:0 @ 0x7fe58a10fcc0] w:1920 h:1080 pixfmt:yuv420p tb:1/1000 fr:24000/1001 sar:1/1
Output #0, mp4, to 'Arrival_t00.mp4':
  Metadata:
    encoder         : Lavf58.45.100
    Chapter #0:0: start 0.000000, end 589.755833
    Metadata:
      title           : Chapter 01
    Chapter #0:1: start 589.755833, end 1053.635917
    Metadata:
      title           : Chapter 02
    Chapter #0:2: start 1053.635917, end 1408.281875
    Metadata:
      title           : Chapter 03
    Chapter #0:3: start 1408.281875, end 2033.990292
    Metadata:
      title           : Chapter 04
    Chapter #0:4: start 2033.990292, end 2461.500708
    Metadata:
      title           : Chapter 05
    Chapter #0:5: start 2461.500708, end 3146.101292
    Metadata:
      title           : Chapter 06
    Chapter #0:6: start 3146.101292, end 3454.534417
    Metadata:
      title           : Chapter 07
    Chapter #0:7: start 3454.534417, end 3786.449333
    Metadata:
      title           : Chapter 08
    Chapter #0:8: start 3786.449333, end 4169.206708
    Metadata:
      title           : Chapter 09
    Chapter #0:9: start 4169.206708, end 4569.398167
    Metadata:
      title           : Chapter 10
    Chapter #0:10: start 4569.398167, end 5121.533083
    Metadata:
      title           : Chapter 11
    Chapter #0:11: start 5121.533083, end 5736.981250
    Metadata:
      title           : Chapter 12
    Chapter #0:12: start 5736.981250, end 6326.320000
    Metadata:
      title           : Chapter 13
    Chapter #0:13: start 6326.320000, end 6982.976000
    Metadata:
      title           : Chapter 14
    Stream #0:0(eng): Video: hevc (hevc_videotoolbox) (hev1 / 0x31766568), yuv420p(bt709), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 8000 kb/s, 23.98 fps, 24k tbn, 23.98 tbc (default)
    Metadata:
      BPS-eng         : 27341256
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 167424
      NUMBER_OF_BYTES-eng: 23865416837
      SOURCE_ID-eng   : 001011
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      encoder         : Lavc58.91.100 hevc_videotoolbox
    Stream #0:1(eng): Audio: ac3 (ac-3 / 0x332D6361), 48000 Hz, 5.1(side), fltp (24 bit), 640 kb/s (default)
    Metadata:
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
      BPS-eng         : 4207353
      DURATION-eng    : 01:56:22.976000000
      NUMBER_OF_FRAMES-eng: 654654
      NUMBER_OF_BYTES-eng: 3672480936
      SOURCE_ID-eng   : 001100
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.15.4 darwin(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2021-02-03 17:58:34
      encoder         : Lavc58.91.100 ac3
[hevc_videotoolbox @ 0x7fe588809800] Color range not set for yuv420p. Using MPEG range.
```

**Comment by donmelton** [comment] 2021-02-11 22:01
@buffaloseven Thanks for the information. But can you also do this at your Terminal prompt:

```
other-transcode --version
```

...and paste the result here? Because grepping through your installed Gems doesn't confirm the version that's actually being executed. Thanks.

Also, I just checked on my iMac running Big Sur with `other-transcode` 0.7.0 using the `--hevc` and `--mp4` options and I'm seeing `-tag:v hvc1` in my `ffmpeg` command line.

So I can't reproduce this.

**Comment by buffaloseven** [comment] 2021-02-11 22:02
Haha, well there's the problem:

```
┕> other-transcode --version
other-transcode 0.3.0
Copyright (c) 2019-2020 Don Melton
```

How did I end up with 0.3.0 when I gem installed it today?

**Comment by donmelton** [comment] 2021-02-11 22:06
@buffaloseven I suspect you installed in the macOS system location instead of your Homebrew location. Possibly using `sudo` or not having your `$PATH` variable set correctly when you did the install. It happens to us all from time to time.

Do you need help fixing that? Or should we close this now?

**Comment by buffaloseven** [comment] 2021-02-11 22:11
Thanks. I must have installed it some time ago? I have no recollection of it, though! I removed it from the system Ruby and added Homebrew Ruby's gem directory into my $PATH and now all is working as should. Thanks for following up with me; sorry for the PBKAC.

**Comment by donmelton** [comment] 2021-02-11 22:13
@buffaloseven No worries. That's why I'm here. I'm glad we were able to find the problem together. 👍 

Closing now.

**Closed by donmelton** 2021-02-11 22:13 UTC
Labels: help wanted
