### ISSUE TITLE
Output to different destination

### ISSUE THREAD

**Issue by mumblequatch** [donmelton/other_video_transcoding#100] opened 2021-02-25 16:11 UTC
On Mac OS, the default output destination appears to be the main folder of the current user. Is there a way to set an alternate output destination, such as an external disk? I don't see a way defined in the help.

**Comment by donmelton** [comment] 2021-02-25 16:27
@mumblequatch The output from `other-transcode` is always placed in the current working directory. This behavior is intentional and by design. And I have no plans to change that. You can already decide where your output will go simply by using the `cd` command to change the current working directory before you invoke `other-transcode`. So it's not a limitation either.

Your question is related to feature requests in issues #9, #44 and #45. I've detailed my reasoning for not implementing this in that first issue and discussed it the other issues. Sorry.

**Comment by mumblequatch** [comment] 2021-02-26 16:54
Makes total sense, Don. Thank you for the clarification!

**Comment by donmelton** [comment] 2021-02-26 20:44
@mumblequatch No problem. I'll close this then.

**Closed by donmelton** 2021-02-26 20:44 UTC
Labels: help wanted, question
